spring:
  application:
    name: uaa-server

eureka:
  instance:
    non-secure-port: 9000
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka/

security:
  basic:
    enabled: false
  user:
    password: password
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**

